name: Build Debian Package
on:
  push:
    branches:
      - master  # Adjust this branch name as needed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Debian package
      working-directory: ../..
      run: |
        # Build the Debian package
        pwd
        fakeroot dpkg-deb --build nemo-actions-for-vscode
        

    - name: Copy .deb file to repository root
      run: |
        # Move the .deb file to the repository root
        cp ../../nemo-actions-for-vscode.deb vscode_nemo_package.deb
        rm ../../nemo-actions-for-vscode.deb

    - name: Upload .deb file
      uses: actions/upload-artifact@v2
      with:
        name: vscode-nemo-package
        path: vscode_nemo_package.deb
